### ISSUE TITLE
Images are in different folders 

### ISSUE THREAD

**Issue by MaxKrog** [osqledaren/osqledaren.se#63]
From osqledare.se/media/uploads... to osqledaren.se/wp-content/uploads

**Comment by MaxKrog** [comment]
Possible solution:

Make a redirect from osqledaren.se/media/X to osqledaren.se/wp-content/X

**Comment by nicolas-lindberg** [comment]
Another solution is to just run a mysql query and replace 'osqledaren.se/media/' with 'osqledaren.se/wp-content/uploads/'
